<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Transaction Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #333;
            font-size: 12px;
            line-height: 1.5;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #edcc94;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #010101;
            text-transform: uppercase;
            letter-spacing: 2px;
        }
        .header p {
            margin: 5px 0 0;
            color: #6b7280;
        }
        .stats {
            margin-bottom: 30px;
            width: 100%;
        }
        .stats td {
            padding: 10px;
            background: #f9f9f9;
            border-radius: 8px;
        }
        .stats-label {
            font-size: 10px;
            text-transform: uppercase;
            color: #6b7280;
            font-weight: bold;
        }
        .stats-value {
            font-size: 16px;
            font-weight: bold;
            color: #010101;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f5f5f5;
            text-align: left;
            padding: 12px 10px;
            font-weight: bold;
            border-bottom: 1px solid #e5e5e5;
            color: #010101;
            font-size: 10px;
            text-transform: uppercase;
        }
        td {
            padding: 10px;
            border-bottom: 1px solid #f0f0f0;
            vertical-align: top;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #9ca3af;
        }
        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: bold;
        }
        .badge-success {
            background-color: #dcfce7;
            color: #166534;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Transaction Report</h1>
        <p>Volare POS — Modern Cashier System</p>
        <p>Date: {{ $date ? \Carbon\Carbon::parse($date)->format('d F Y') : 'All Time' }}</p>
    </div>

    <table class="stats">
        <tr>
            <td width="33%">
                <div class="stats-label">Total Transactions</div>
                <div class="stats-value">{{ count($orders) }}</div>
            </td>
            <td width="33%">
                <div class="stats-label">Total Revenue</div>
                <div class="stats-value">Rp {{ number_format($orders->sum('total_amount'), 0, ',', '.') }}</div>
            </td>
            <td width="33%">
                <div class="stats-label">Total Profit</div>
                <div class="stats-value">Rp {{ number_format($orders->sum('profit'), 0, ',', '.') }}</div>
            </td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Order ID</th>
                <th>Date & Time</th>
                <th>Cashier</th>
                <th class="text-right">Total</th>
                <th class="text-right">Profit</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td><strong>ORD-{{ str_pad($order->id, 4, '0', STR_PAD_LEFT) }}</strong></td>
                <td>
                    {{ $order->created_at->format('d M Y') }}<br>
                    <small style="color: #6b7280">{{ $order->created_at->format('H:i') }}</small>
                </td>
                <td>{{ $order->cashier->name ?? 'System' }}</td>
                <td class="text-right">Rp {{ number_format($order->total_amount, 0, ',', '.') }}</td>
                <td class="text-right" style="color: #166534">Rp {{ number_format($order->profit, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Volare POS on {{ now()->format('d M Y, H:i') }}
    </div>
</body>
</html>
